export const apiKey = '4bde3e55b371430a8e5195439260503';

export const theme = {
    bgWhite: opacity => `rgba(255, 255, 255, ${opacity})`
}

export const weatherImages = {
'Partly Cloudy': require('../assets/weather/partly-cloudy.png'),
'Partly Cloudy ': require('../assets/weather/partly-cloudy.png'),
'Partly cloudy': require('../assets/weather/partly-cloudy.png'),
'Moderate rain': require('../assets/weather/moderate-rain.png'),
'Moderate Rain': require('../assets/weather/moderate-rain.png'),
'Moderate rain ': require('../assets/weather/moderate-rain.png'),
'Patchy rain possible': require('../assets/weather/patchy-rain-possible.png'),
'Patchy Rain Possible': require('../assets/weather/patchy-rain-possible.png'),
'Patchy rain possible ': require('../assets/weather/patchy-rain-possible.png'),
'Patchy light rain': require('../assets/weather/patchy-rain-possible.png'),
'Patchy Light Rain': require('../assets/weather/patchy-rain-possible.png'),
'Patchy light rain ': require('../assets/weather/patchy-rain-possible.png'),
'Patchy snow possible': require('../assets/weather/heavy-rain-times.png'),
'Patchy Snow Possible': require('../assets/weather/heavy-rain-times.png'),
'Patchy snow possible ': require('../assets/weather/heavy-rain-times.png'),
'Patchy sleet possible': require('../assets/weather/heavy-rain-times.png'),
'Patchy Sleet Possible': require('../assets/weather/heavy-rain-times.png'),
'Patchy sleet possible ': require('../assets/weather/heavy-rain-times.png'),
'Patchy freezing drizzle possible': require('../assets/weather/heavy-rain-times.png'),
'Patchy Freezing Drizzle Possible': require('../assets/weather/heavy-rain-times.png'),
'Patchy freezing drizzle possible ': require('../assets/weather/heavy-rain-times.png'),
'Freezing fog': require('../assets/weather/heavy-rain-times.png'),
'Freezing Fog': require('../assets/weather/heavy-rain-times.png'),
'Freezing fog ': require('../assets/weather/heavy-rain-times.png'),
'Patchy light drizzle': require('../assets/weather/heavy-rain-times.png'),
'Patchy Light Drizzle': require('../assets/weather/heavy-rain-times.png'),
'Patchy light drizzle ': require('../assets/weather/heavy-rain-times.png'),
'Light drizzle': require('../assets/weather/heavy-rain-times.png'),
'Light Drizzle': require('../assets/weather/heavy-rain-times.png'),
'Light drizzle ': require('../assets/weather/heavy-rain-times.png'),
'Heavy freezing drizzle': require('../assets/weather/heavy-rain-times.png'),
'Heavy Freezing Drizzle': require('../assets/weather/heavy-rain-times.png'),
'Heavy freezing drizzle ': require('../assets/weather/heavy-rain-times.png'),
'Blowing snow': require('../assets/weather/heavy-rain-times.png'),
'Blowing Snow': require('../assets/weather/heavy-rain-times.png'),
'Blowing snow ': require('../assets/weather/heavy-rain-times.png'),
'Blizzard': require('../assets/weather/heavy-rain-times.png'),
'Blizzard ': require('../assets/weather/heavy-rain-times.png'),
'Patchy rain nearby': require('../assets/weather/patchy-rain-possible.png'),
'Patchy Rain Nearby': require('../assets/weather/patchy-rain-possible.png'),
'Patchy rain nearby ': require('../assets/weather/patchy-rain-possible.png'),
'Light rain shower': require('../assets/weather/patchy-rain-possible.png'),
'Light Rain Shower': require('../assets/weather/patchy-rain-possible.png'),
'Light rain shower ': require('../assets/weather/patchy-rain-possible.png'),
'Moderate or heavy rain shower': require('../assets/weather/moderate-heavy-rain-shower.png'),
'Moderate Or Heavy Rain Shower': require('../assets/weather/moderate-heavy-rain-shower.png'),
'Moderate or heavy rain shower ': require('../assets/weather/moderate-heavy-rain-shower.png'),
'Torrential rain shower': require('../assets/weather/heavy-rain.png'),
'Torrential Rain Shower': require('../assets/weather/heavy-rain.png'),
'Torrential rain shower ': require('../assets/weather/heavy-rain.png'),
'Light sleet showers': require('../assets/weather/heavy-rain.png'),
'Light Sleet Showers': require('../assets/weather/heavy-rain.png'),
'Light sleet showers ': require('../assets/weather/heavy-rain.png'),
'Moderate or heavy sleet showers': require('../assets/weather/heavy-rain.png'),
'Moderate Or Heavy Sleet Showers': require('../assets/weather/heavy-rain.png'),
'Moderate or heavy sleet showers ': require('../assets/weather/heavy-rain.png'),
'Moderate or heavy snow showers': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate Or Heavy Snow Showers': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy snow showers ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Ice pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Ice Pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Ice pellets ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light showers of ice pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light Showers Of Ice Pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light showers of ice pellets ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy showers of ice pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate Or Heavy Showers Of Ice Pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy showers of ice pellets ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Sunny': require('../assets/weather/sunny.png'),
'Sunny ': require('../assets/weather/sunny.png'),
'Clear': require('../assets/weather/clear.png'),
'Clear ': require('../assets/weather/clear.png'),
'Overcast': require('../assets/weather/overcast.png'),
'Overcast ': require('../assets/weather/overcast.png'),
'Mist': require('../assets/weather/overcast.png'),
'Mist ': require('../assets/weather/overcast.png'),
'Fog': require('../assets/weather/overcast.png'),
'Fog ': require('../assets/weather/overcast.png'),
'Cloudy': require('../assets/weather/cloudy.png'),
'Cloudy ': require('../assets/weather/cloudy.png'),
'Light rain': require('../assets/weather/light-rain.png'),
'Light Rain': require('../assets/weather/light-rain.png'),
'Light rain ': require('../assets/weather/light-rain.png'),
'Moderate rain at times': require('../assets/weather/moderate-rain-times.png'),
'Moderate Rain At Times': require('../assets/weather/moderate-rain-times.png'),
'Moderate rain at times ': require('../assets/weather/moderate-rain-times.png'),
'Heavy rain': require('../assets/weather/heavy-rain.png'),
'Heavy Rain': require('../assets/weather/heavy-rain.png'),
'Heavy rain ': require('../assets/weather/heavy-rain.png'),
'Heavy rain at times': require('../assets/weather/heavy-rain-times.png'),
'Heavy Rain At Times': require('../assets/weather/heavy-rain-times.png'),
'Heavy rain at times ': require('../assets/weather/heavy-rain-times.png'),
'Moderate or heavy freezing rain': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate Or Heavy Freezing Rain': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy freezing rain ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light sleet': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light Sleet': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light sleet ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy sleet': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate Or Heavy Sleet': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy sleet ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy light snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy Light Snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy light snow ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light Snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light snow ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light freezing rain': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light Freezing Rain': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Light freezing rain ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy moderate snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy Moderate Snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy moderate snow ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate Snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate snow ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy heavy snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy Heavy Snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Patchy heavy snow ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Heavy snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Heavy Snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Heavy snow ': require('../assets/weather/moderate-heavy-freezing-rain.png'),
'Moderate or heavy rain with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Moderate Or Heavy Rain With Thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Moderate or heavy rain with thunder ': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Thundery outbreaks in nearby': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Thundery Outbreaks In Nearby': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Thundery outbreaks in nearby ': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Patchy light rain with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Patchy Light Rain With Thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Patchy light rain with thunder ': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Patchy light snow with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Patchy Light Snow With Thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Patchy light snow with thunder ': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Moderate or heavy snow with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Moderate Or Heavy Snow With Thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'Moderate or heavy snow with thunder ': require('../assets/weather/moderate-heavy-rain-thunder.png'),
'other': require('../assets/weather/other.png'),
}

/* export const weatherImages = {
    'Partly cloudy': require('../assets/weather/partly-cloudy.png'),
    'Partly Cloudy ': require('../assets/weather/partly-cloudy.png'),
    'Moderate rain': require('../assets/weather/moderate-rain.png'),
    'Patchy rain possible': require('../assets/weather/patchy-rain-possible.png'),
    'Patchy light rain': require('../assets/weather/patchy-rain-possible.png'),
    'Patchy snow possible': require('../assets/weather/heavy-rain-times.png'),
    'Patchy sleet possible': require('../assets/weather/heavy-rain-times.png'),
    'Patchy freezing drizzle possible': require('../assets/weather/heavy-rain-times.png'),
    'Freezing fog': require('../assets/weather/heavy-rain-times.png'),
    'Patchy light drizzle': require('../assets/weather/heavy-rain-times.png'),
    'Light drizzle': require('../assets/weather/heavy-rain-times.png'),
    'Heavy freezing drizzle': require('../assets/weather/heavy-rain-times.png'),
    'Blowing snow': require('../assets/weather/heavy-rain-times.png'),
    'Blizzard': require('../assets/weather/heavy-rain-times.png'),
    'Patchy rain nearby': require('../assets/weather/patchy-rain-possible.png'),
    'Light rain shower': require('../assets/weather/patchy-rain-possible.png'),
    'Moderate or heavy rain shower': require('../assets/weather/heavy-rain.png'),
    'Torrential rain shower': require('../assets/weather/heavy-rain.png'),
    'Light sleet showers': require('../assets/weather/heavy-rain.png'),
    'Moderate or heavy sleet showers': require('../assets/weather/heavy-rain.png'),
    'Moderate or heavy snow showers': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Ice pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Light showers of ice pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Moderate or heavy showers of ice pellets': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Sunny': require('../assets/weather/sunny.png'),
    'Sunny ': require('../assets/weather/sunny.png'),
    'Clear': require('../assets/weather/clear.png'),
    'Overcast': require('../assets/weather/overcast.png'),
    'Overcast ': require('../assets/weather/overcast.png'),
    'Mist': require('../assets/weather/overcast.png'),
    'Fog': require('../assets/weather/overcast.png'),
    'Cloudy': require('../assets/weather/cloudy.png'),
    'Light rain': require('../assets/weather/light-rain.png'),
    'Moderate rain at times': require('../assets/weather/moderate-rain-times.png'),
    'Heavy rain': require('../assets/weather/heavy-rain.png'),
    'Heavy rain at times': require('../assets/weather/heavy-rain-times.png'),
    'Moderate or heavy freezing rain': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Light sleet': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Moderate or heavy sleet': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Patchy light snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Light snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Light freezing rain': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Patchy moderate snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Moderate snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Patchy heavy snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Heavy snow': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Freezing fog': require('../assets/weather/moderate-heavy-freezing-rain.png'),
    'Moderate or heavy rain shower': require('../assets/weather/moderate-heavy-rain-shower.png'),
    'Moderate or heavy rain with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
    'Thundery outbreaks in nearby': require('../assets/weather/moderate-heavy-rain-thunder.png'),
    'Patchy light rain with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
    'Patchy light snow with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
    'Moderate or heavy snow with thunder': require('../assets/weather/moderate-heavy-rain-thunder.png'),
    'other': require('../assets/weather/other.png'),
} */